[package]
name = "qdbr"
version = "0.1.0"
edition = "2021"

[lib]
name = "questdbr"
crate-type = ["dylib"]

[dependencies]
jni = "0.21.1"

[workspace.metadata.cross.target.x86_64-pc-windows-gnu]
xargo = false
build-std = false
